// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3LaiFFMFJjgfNUol-xEMp3DhMMnkz5BA',
    appId: '1:864378831475:web:d60722a90efd302da16006',
    messagingSenderId: '864378831475',
    projectId: 'wlotim',
    authDomain: 'wlotim.firebaseapp.com',
    storageBucket: 'wlotim.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkAvSGdX3RrfigXZHhroRrghU2XVQ9EwU',
    appId: '1:864378831475:android:a12bd56c59f866b4a16006',
    messagingSenderId: '864378831475',
    projectId: 'wlotim',
    storageBucket: 'wlotim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA64Ynd2yIvxxB2R2JbRwEnVdgw5m44Cj0',
    appId: '1:864378831475:ios:d8239caf9447756ca16006',
    messagingSenderId: '864378831475',
    projectId: 'wlotim',
    storageBucket: 'wlotim.appspot.com',
    iosClientId: '864378831475-17csjcjc0lv1gcv7ahpbvagudgkvtgdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.wlotim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA64Ynd2yIvxxB2R2JbRwEnVdgw5m44Cj0',
    appId: '1:864378831475:ios:d8239caf9447756ca16006',
    messagingSenderId: '864378831475',
    projectId: 'wlotim',
    storageBucket: 'wlotim.appspot.com',
    iosClientId: '864378831475-17csjcjc0lv1gcv7ahpbvagudgkvtgdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.wlotim',
  );
}
